--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 21.01.2020 15:05:53
-- Server version: 8.0.17
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE university;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Drop table `lector`
--
DROP TABLE IF EXISTS lector;

--
-- Set default database
--
USE university;

--
-- Create table `lector`
--
CREATE TABLE lector (
  id INT(11) NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  degree ENUM('ASSISTANT','ASSOCIATE_PROFESSOR','PROFESSOR') NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `department`
--
CREATE TABLE department (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table lector
--
INSERT INTO lector VALUES
(1, 'Inge', 'Klarts', 'ASSISTANT'),
(3, 'Leon', 'Neumann', 'PROFESSOR'),
(5, 'James', 'Brown', 'ASSOCIATE_PROFESSOR'),
(6, 'Inge', 'Klarts', 'ASSISTANT'),
(7, 'Max', 'Klein', 'ASSOCIATE_PROFESSOR'),
(8, 'Leon', 'Vic', 'PROFESSOR'),
(9, 'Moriz', 'Petrov', 'PROFESSOR'),
(10, 'James', 'Brown', 'ASSOCIATE_PROFESSOR'),
(11, 'Inge', 'Klarts', 'ASSISTANT'),
(12, 'Max', 'Klein', 'ASSOCIATE_PROFESSOR'),
(13, 'Leon', 'Vic', 'PROFESSOR'),
(14, 'Moriz', 'Petrov', 'PROFESSOR'),
(15, 'James', 'Brown', 'ASSOCIATE_PROFESSOR');

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
(1, 'NHJD'),
(3, 'IHSN'),
(5, 'HTCS'),
(6, 'NHJD'),
(7, 'SRYS'),
(8, 'YTFD'),
(9, 'TYGD'),
(10, 'HTCS');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;